//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Collidable : Enemy, Player
{
	public virtual object mass
	{
		get;
		set;
	}

	public virtual object boudingbox
	{
		get;
		set;
	}

	public virtual void collide(object Colidable)
	{
		throw new System.NotImplementedException();
	}

	public virtual void isColliding(object Collidable)
	{
		throw new System.NotImplementedException();
	}

}

