//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Distraction
{
	public virtual object isDistracting
	{
		get;
		set;
	}

	public virtual object frequency
	{
		get;
		set;
	}

	public virtual object cooldown
	{
		get;
		set;
	}

	public virtual Distractiontype Enumeration1
	{
		get;
		set;
	}

}

