//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Enemy
{
	public virtual object difficulty
	{
		get;
		set;
	}

	public virtual EnemyType EnemyType
	{
		get;
		set;
	}

	public virtual void spawn()
	{
		throw new System.NotImplementedException();
	}

	public virtual void despawn()
	{
		throw new System.NotImplementedException();
	}

}

