//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Engine
{
	public virtual object Game main
	{
		get;
		set;
	}

	public virtual Game Game
	{
		get;
		set;
	}

	public virtual void init()
	{
		throw new System.NotImplementedException();
	}

	public virtual void mainLoop()
	{
		throw new System.NotImplementedException();
	}

}

