//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>typeid differs between objects</remarks>
public class Entity : Collidable, Distraction
{
	public virtual object typeid
	{
		get;
		set;
	}

	public virtual object velocity
	{
		get;
		set;
	}

	public virtual void draw()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update()
	{
		throw new System.NotImplementedException();
	}

}

