//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Game
{
	public virtual object entity[]
	{
		get;
		set;
	}

	public virtual object Attribute1
	{
		get;
		set;
	}

	public virtual object highscore
	{
		get;
		set;
	}

	public virtual object collision[]
	{
		get;
		set;
	}

	public virtual Entity Entity
	{
		get;
		set;
	}

	public virtual void draw()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update(object double delta)
	{
		throw new System.NotImplementedException();
	}

	public virtual void init()
	{
		throw new System.NotImplementedException();
	}

	public virtual void save/load highscore()
	{
		throw new System.NotImplementedException();
	}

}

